#!/bin/bash

if [ -f /home/slides/content/slides.adoc ]
then
    base=slides
    handouts=handouts
else
    base=$BASENAME
    handouts=$BASENAME
fi

if [ -f /home/slides/content/${base}-docinfo.xml ]
then
  cp /home/slides/content/${base}-docinfo.xml /home/slides/slides-docinfo.xml
else
  rm /home/slides/${base}-docinfo.xml
fi

sed -ri "s/slides\.adoc/${base}.adoc/" /home/slides/slides.adoc

# Generate DocBook file
asciidoctor \
  -a handouts \
  -a data-uri! \
  -a revdate="$(git show -s --format=%cd --date=format:%d.%m.%Y)@" \
  -a revnumber="$(git describe)@" \
  -b docbook \
  -d book \
  -o /home/slides/${handouts}.xml \
  /home/slides/slides.adoc

# Transform DocBook file to PDF
fopub \
  -t /home/slides/docbook-xsl-custom \
  /home/slides/${handouts}.xml "$@"

# Export via volume
mv /home/slides/${handouts}.pdf /home/slides/handouts/
