#!/bin/bash

if [[ "${TRACKING}" != "1" ]]; then
    rm /home/slides/slides-docinfo-footer.html
fi

if [ -f /home/slides/content/slides.adoc ]
then
    reveal-ck serve
else
    /usr/local/bin/handouts

    while (true)
    do
        inotifywait -e move -e modify -e create -e delete -r --format "%e %f" --exclude '.*___jb_tmp___' /home/slides/content/ /home/slides/images/
        /usr/local/bin/handouts
    done
fi
