#!/bin/bash

if [ -f /home/slides/content/slides.adoc ]
then
    reveal-ck serve
else
    /usr/local/bin/handouts

    while (true)
    do
        inotifywait -e MOVE_SELF -e modify /home/slides/content/ /home/slides/images/
        /usr/local/bin/handouts
    done
fi
